# Site settings
title: "kllmctrl"
description: "tech sharing"
baseurl: "/" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "kllmctrl"

permalink: /:categories/:title/

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics: UA-64162955-2
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]

gems:
    -jekyll-seo-tag


